### ISSUE TITLE
Cannot load gem?

### ISSUE THREAD

**Issue by popmechanic** [benschwarz/smoke#2]
I've got the gem installed but my irb mic check is failing:

require 'rubygems'
=> true 

require 'benschwarz-smoke'
=> LoadError: no such file to load -- benschwarz-smoke
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'

Got any ideas about what's up here?

**Comment by benschwarz** [comment]
require "smoke" 
will do the job

**Comment by popmechanic** [comment]
=> true

(yay!)

**Comment by benschwarz** [comment]
Perhaps its worth keeping things like this outside of issues. Message me with any questions you might have.
